spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 409915cf48a47370a92cea926084d5a1
            client-secret: Izuv0Yi82kndHrc0zc4j3Y2FQ16UGdb0
            redirect-uri: "{baseUrl}/buyer/{action}/oauth2/kakao/{registrationId}"
            client-name: Kakao
            client-authentication-method: client_secret_post # 다른 서비스와 달리 카카오는 필수 파라미터 값들을 담아 POST로만 요청 가능
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token # 토큰 얻는 uri
            user-info-uri: https://kapi.kakao.com/v2/user/me # 토큰을 이용해 사용자의 정보를 가져오는 uri
            user-info-authentication-method: header
            user_name_attribute: id